# Generated by Django 5.2.4 on 2025-07-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_address_user_city_user_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='twitter',
            new_name='facebook',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
    ]
