# Generated by Django 5.2.4 on 2025-07-27 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeUserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.CharField(max_length=500)),
                ('current_action', models.CharField(blank=True, max_length=100)),
                ('session_key', models.CharField(max_length=40)),
                ('ip_address', models.GenericIPAddressField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_time_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Real-time User Activity',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('file_upload', 'File Upload'), ('file_download', 'File Download'), ('file_delete', 'File Delete'), ('file_share', 'File Share'), ('profile_update', 'Profile Update'), ('password_change', 'Password Change'), ('login', 'Login'), ('logout', 'Logout'), ('search', 'Search'), ('export', 'Export'), ('preview', 'Preview'), ('contact_form', 'Contact Form')], max_length=50)),
                ('action_data', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('session_key', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('file_upload_error', 'File Upload Error'), ('processing_error', 'Processing Error'), ('validation_error', 'Validation Error'), ('export_error', 'Export Error'), ('authentication_error', 'Authentication Error'), ('permission_error', 'Permission Error'), ('system_error', 'System Error')], max_length=50)),
                ('error_message', models.TextField()),
                ('error_details', models.JSONField(default=dict)),
                ('page_url', models.CharField(max_length=500)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Errors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=500)),
                ('page_name', models.CharField(max_length=100)),
                ('session_key', models.CharField(max_length=40)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('time_spent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Page Views',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('pages_visited', models.IntegerField(default=0)),
                ('actions_performed', models.IntegerField(default=0)),
                ('files_uploaded', models.IntegerField(default=0)),
                ('files_downloaded', models.IntegerField(default=0)),
                ('searches_performed', models.IntegerField(default=0)),
                ('exports_created', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Engagement',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('avg_session_duration', models.FloatField(default=0.0)),
                ('avg_pages_per_session', models.FloatField(default=0.0)),
                ('avg_actions_per_session', models.FloatField(default=0.0)),
                ('file_upload_success_rate', models.FloatField(default=0.0)),
                ('file_processing_success_rate', models.FloatField(default=0.0)),
                ('export_success_rate', models.FloatField(default=0.0)),
                ('error_rate', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Performance',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
