# Generated by Django 5.2.4 on 2025-07-26 07:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('kml', 'KML File'), ('csv', 'CSV File'), ('shapefile', 'Shapefile'), ('geojson', 'GeoJSON'), ('excel', 'Excel File'), ('pdf', 'PDF Document'), ('image', 'Image File'), ('other', 'Other File')], max_length=20)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('validated', 'Validated')], default='pending', max_length=20)),
                ('processing_started', models.DateTimeField(blank=True, null=True)),
                ('processing_completed', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_type', models.CharField(choices=[('public', 'Public Link'), ('private', 'Private Link'), ('email', 'Email Share'), ('expiring', 'Expiring Link')], max_length=20)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('shared_with_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('download_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('current_downloads', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to=settings.AUTH_USER_MODEL)),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='userdashboard.fileupload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_type', models.CharField(choices=[('validation', 'File Validation'), ('parsing', 'File Parsing'), ('conversion', 'File Conversion'), ('analysis', 'Data Analysis'), ('export', 'File Export')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('validated', 'Validated')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='userdashboard.fileupload')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FileValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('kml', 'KML File'), ('csv', 'CSV File'), ('shapefile', 'Shapefile'), ('geojson', 'GeoJSON'), ('excel', 'Excel File'), ('pdf', 'PDF Document'), ('image', 'Image File'), ('other', 'Other File')], max_length=20)),
                ('rule_name', models.CharField(max_length=100)),
                ('rule_description', models.TextField()),
                ('max_file_size_mb', models.PositiveIntegerField(default=10)),
                ('allowed_extensions', models.JSONField(default=list)),
                ('required_fields', models.JSONField(blank=True, default=list)),
                ('validation_regex', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['file_type', 'rule_name'],
                'unique_together': {('file_type', 'rule_name')},
            },
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['user', 'file_type'], name='userdashboa_user_id_e4de48_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['status', 'created_at'], name='userdashboa_status_80d220_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['file_type', 'status'], name='userdashboa_file_ty_868574_idx'),
        ),
        migrations.AddIndex(
            model_name='fileshare',
            index=models.Index(fields=['share_token'], name='userdashboa_share_t_dddead_idx'),
        ),
        migrations.AddIndex(
            model_name='fileshare',
            index=models.Index(fields=['expires_at'], name='userdashboa_expires_d87472_idx'),
        ),
    ]
