# Generated by Django 5.2.4 on 2025-07-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0002_fileupload_fileshare_fileprocessinglog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmldata',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='administrative_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='altitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='altitude_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='atom_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='atom_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='extended_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='extrude',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='locality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='open_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='snippet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='style_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='style_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='sub_administrative_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='sub_locality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='tessellate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='thoroughfare',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='time_begin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='time_end',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='time_when',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='visibility',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='kmldata',
            name='xal_address_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='kmldata',
            index=models.Index(fields=['kml_file', 'geometry_type'], name='userdashboa_kml_fil_a9c05f_idx'),
        ),
        migrations.AddIndex(
            model_name='kmldata',
            index=models.Index(fields=['kitta_number'], name='userdashboa_kitta_n_f4d956_idx'),
        ),
        migrations.AddIndex(
            model_name='kmldata',
            index=models.Index(fields=['owner_name'], name='userdashboa_owner_n_a4ae20_idx'),
        ),
    ]
