# Generated by Django 5.2.4 on 2025-07-26 08:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0003_kmldata_address_kmldata_administrative_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='bounds',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='coordinate_system',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='feature_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='geometry_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('geometry_type', models.CharField(blank=True, max_length=50, null=True)),
                ('coordinates', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_data', to='userdashboard.fileupload')),
            ],
            options={
                'ordering': ['row_number'],
                'indexes': [models.Index(fields=['file_upload', 'row_number'], name='userdashboa_file_up_dca1d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='FileConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversion_type', models.CharField(choices=[('kml_to_csv', 'KML to CSV'), ('kml_to_shapefile', 'KML to Shapefile'), ('csv_to_kml', 'CSV to KML'), ('csv_to_shapefile', 'CSV to Shapefile'), ('shapefile_to_kml', 'Shapefile to KML'), ('shapefile_to_csv', 'Shapefile to CSV')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='exports/')),
                ('output_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('processing_started', models.DateTimeField(auto_now_add=True)),
                ('processing_completed', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='userdashboard.fileupload')),
            ],
            options={
                'ordering': ['-processing_started'],
                'indexes': [models.Index(fields=['source_file', 'conversion_type'], name='userdashboa_source__bb51c6_idx'), models.Index(fields=['status', 'processing_started'], name='userdashboa_status_d20dc7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShapefileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.PositiveIntegerField()),
                ('geometry_type', models.CharField(max_length=50)),
                ('coordinates', models.TextField()),
                ('attributes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapefile_data', to='userdashboard.fileupload')),
            ],
            options={
                'ordering': ['feature_id'],
                'indexes': [models.Index(fields=['file_upload', 'feature_id'], name='userdashboa_file_up_67f552_idx')],
            },
        ),
    ]
