# Generated by Django 5.2.4 on 2025-07-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0006_uploadedparcel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kmldata',
            name='website',
        ),
    ]
