# Generated by Django 5.2.4 on 2025-07-29 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0007_remove_kmldata_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyHistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('upload', 'File Upload'), ('filter', 'Filter Applied'), ('export', 'PDF Export'), ('download', 'File Download'), ('delete', 'File Deleted')], max_length=10)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, max_length=10, null=True)),
                ('filters_applied', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('record_count', models.IntegerField(default=0)),
                ('map_coordinates_count', models.IntegerField(default=0)),
                ('export_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey History Log',
                'verbose_name_plural': 'Survey History Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
